###Nicholas Pollender
###doctorOffice.rest
###Contains API function calls, for troubleshooting.

###GET FUNCTIONS

GET http://localhost:3000/doctorOffice/providers

###

GET http://localhost:3000/doctorOffice/avail/all

###

GET http://localhost:3000/doctorOffice/appt/all

###

GET http://localhost:3000/doctorOffice/clinic

###

GET http://localhost:3000/doctorOffice/patients/all

###
###Date format: YYYY-MM-DD
###Provider via ID: LastnameFirstname
###

GET http://localhost:3000/doctorOffice/avail
Content-Type: application/json

{
    "startDay": "",
    "endDay": "",
    "provider": ""
}

###POST FUNCTIONS

POST http://localhost:3000/doctorOffice/clinic/CLINIC_NAME

###

POST http://localhost:3000/doctorOffice/providers
Content-Type: application/json

{
    "firstName": "",
    "lastName": ""
}

###
###Date format: YYYY-MM-DD
###Time format: hh:mm
###Provider/Patient via ID: LastnameFirstname
###

POST http://localhost:3000/doctorOffice/appt
Content-Type: application/json

{
    "date": "",
    "startTime": "",
    "endTime": "",
    "provider": "",
    "patient": ""
}

###

POST http://localhost:3000/doctorOffice/patients
Content-Type: application/json

{
    "firstName": "",
    "lastName": ""
}

###
###Date format: YYYY-MM-DD
###Time format: hh:mm
###Provider via ID: LastnameFirstname
###

POST http://localhost:3000/doctorOffice/avail
Content-Type: application/json

{
    "startTime": "",
    "endTime": "",
    "date": "",
    "provider": ""
}

###DELETE FUNCTIONS

DELETE http://localhost:3000/doctorOffice/providers/LastnameFirstname